# src/chunkshop/oauth/base.py
from __future__ import annotations
from typing import Protocol, runtime_checkable
from chunkshop.oauth.tokens import OAuthTokens


@runtime_checkable
class OAuthProvider(Protocol):
    def authorization_url(self, state: str, redirect_uri: str, scopes: list[str]) -> str: ...
    def exchange_code(self, code: str, redirect_uri: str) -> OAuthTokens: ...
    def refresh_token(self, refresh_token: str) -> OAuthTokens: ...
    def validate_scopes(self, tokens: OAuthTokens, required: list[str]) -> bool: ...
